# Generated by Django 5.2.7 on 2025-10-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0005_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='reply_sent',
            field=models.BooleanField(default=False),
        ),
    ]
