# Generated by Django 5.2.7 on 2025-10-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0007_remove_contactmessage_phone_branch_website_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='branch',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude of the branch location (e.g., 30.2672)', null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude of the branch location (e.g., -97.7431)', null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
