# Generated by Django 5.2.7 on 2025-10-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0008_remove_branch_updated_at_branch_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='longitude',
        ),
        migrations.AddField(
            model_name='branch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
