# Generated by Django 5.2.7 on 2025-10-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0009_remove_branch_latitude_remove_branch_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='CarouselImage',
        ),
    ]
