# Generated by Django 5.2.7 on 2025-10-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0010_alter_branch_phone_delete_carouselimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='data_limit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('business', 'Business')], max_length=50),
        ),
    ]
